# @package _global_
#
scene_ids:
  - Beechwood_0_int
  - Beechwood_1_int
  - Benevolence_0_int
  - Benevolence_1_int
  # - Benevolence_2_int
  - Ihlen_0_int
  # - Ihlen_1_int
  - Merom_0_int
  # - Merom_1_int
  # - Pomaria_0_int
  - Pomaria_1_int
  # - Pomaria_2_int
  # - Rs_int
  - Wainscott_0_int
  # - Wainscott_1_int

num_envs: 8
