name: ssg
channels:
  - pytorch
  - conda-forge
  - nvidia
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pytorch==1.9.1
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - gym=0.21
  - hydra-core
  - pdbpp
  - tensorboard
  - grpcio=1.43.0
  - dvc-s3
  - numba
  - ffmpeg > 4.4
  - numpy=1.20.3
  - pip:
    - https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_scatter-2.0.9-cp38-cp38-linux_x86_64.whl
    - https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_sparse-0.6.12-cp38-cp38-linux_x86_64.whl
    - https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_cluster-1.5.9-cp38-cp38-linux_x86_64.whl
    - https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_spline_conv-1.2.1-cp38-cp38-linux_x86_64.whl
    - torch-geometric
    - hydra-submitit-launcher
    - ray[rllib,defaults]
    - open3d>=0.14.1
    - loguru
