from ssg.utils.other_utils import convert_to_onehot

ROOMS = [
    "bathroom",
    "bedroom",
    "childs_room",
    "closet",
    "corridor",
    "dining_room",
    "empty_room",
    "exercise_room",
    "garage",
    "home_office",
    "kitchen",
    "living_room",
    "lobby",
    "pantry_room",
    "playroom",
    "staircase",
    "storage_room",
    "television_room",
    "utility_room",
    # rooms below are not in the 15 scenes
    "balcony",
    "library",
    "auditorium",
    "undefined",
]


EXTERIOR_DOORS = {
    "Beechwood_0_int": ['door_93', 'door_109'],
    "Beechwood_1_int": [],
    "Benevolence_0_int": ['door_9', 'door_12', 'door_13'],
    "Benevolence_1_int": ['door_52'],
    "Benevolence_2_int": [],
    "Ihlen_0_int": ['door_42'],
    "Ihlen_1_int": ['door_86', 'door_91'],
    "Merom_0_int": ['door_60'],
    "Merom_1_int": ['door_74', 'door_93'],
    "Pomaria_0_int": ['door_41', 'door_42'],
    "Pomaria_1_int": ['door_65', 'door_70'],
    "Pomaria_2_int": [],
    "Rs_int": [],
    "Wainscott_0_int": ['door_126', 'door_128', 'door_132', 'door_135'],
    "Wainscott_1_int": [],
}

TRAVERSABLE_MAP = {
    'Rs_int': {
        'bathroom_0': ['bedroom_0'],
        'bedroom_0': ['bathroom_0', 'living_room_0'],
        'kitchen_0': ['lobby_0'],
        'living_room_0': ['bedroom_0', 'lobby_0'],
        'lobby_0': ['kitchen_0', 'living_room_0'],
    },
    'Wainscott_0_int': {
        'bathroom_0': ['living_room_2'],
        'bathroom_1': ['dining_room_1', 'living_room_2'],
        'bedroom_0': ['dining_room_1'],
        'dining_room_0': ['kitchen_0', 'living_room_1'],
        'dining_room_1': ['bathroom_1', 'bedroom_0', 'living_room_2'],
        'kitchen_0': ['dining_room_0', 'living_room_0'],
        'living_room_0': ['kitchen_0', 'living_room_1'],
        'living_room_1': ['dining_room_0', 'living_room_0', 'living_room_2'],
        'living_room_2': ['bathroom_0', 'bathroom_1', 'dining_room_1', 'living_room_1'],
    },
    'Beechwood_0_int': {
        'bathroom_0': ['corridor_0'],
        'corridor_0': ['bathroom_0', 'home_office_0', 'kitchen_0', 'lobby_0', 'storage_room_0', 'utility_room_0'],
        'dining_room_0': ['lobby_0'],
        'home_office_0': ['corridor_0'],
        'kitchen_0': ['corridor_0', 'living_room_0'],
        'living_room_0': ['kitchen_0'],
        'lobby_0': ['corridor_0', 'dining_room_0'],
        'storage_room_0': ['corridor_0'],
        # 'staircase_0': [],
        'utility_room_0': ['corridor_0'],
    },
    'Beechwood_1_int': {
        'bathroom_0': ['corridor_0', 'playroom_0'],
        'bathroom_1': ['bedroom_0', 'closet_0'],
        'bedroom_0': ['bathroom_1', 'corridor_0'],
        'childs_room_0': ['corridor_0'],
        'childs_room_1': ['corridor_0', 'playroom_0'],
        'closet_0': ['bathroom_1'],
        'corridor_0': ['bathroom_0', 'bedroom_0', 'childs_room_0', 'childs_room_1', 'television_room_0'],
        'playroom_0': ['bathroom_0', 'childs_room_1'],
        'television_room_0': ['corridor_0'],
    },
    'Benevolence_0_int': {
        'bathroom_0': ['empty_room_0'],
        'corridor_0': ['empty_room_0', 'lobby_0'],
        'empty_room_0': ['bathroom_0', 'corridor_0'],
        'lobby_0': ['corridor_0']
    },
    'Benevolence_1_int': {
        'corridor_0': ['dining_room_0', 'living_room_0', 'storage_room_0'],
        'dining_room_0': ['corridor_0', 'kitchen_0', 'living_room_0'],
        'kitchen_0': ['dining_room_0'],
        'living_room_0': ['corridor_0', 'dining_room_0'],
        'storage_room_0': ['corridor_0']
    },
    'Benevolence_2_int': {
        'bathroom_0': ['bedroom_0'],
        'bathroom_1': ['bedroom_1'],
        'bedroom_0': ['bathroom_0', 'corridor_0'],
        'bedroom_1': ['bathroom_1', 'corridor_0'],
        'corridor_0': ['bedroom_0', 'bedroom_1'],
    },
    'Ihlen_0_int': {
        'bathroom_0': ['storage_room_0'],
        'corridor_0': ['living_room_0', 'storage_room_0'],
        'dining_room_0': ['living_room_0'],
        'garage_0': ['storage_room_0'],
        'living_room_0': ['corridor_0', 'dining_room_0'],
        'storage_room_0': ['bathroom_0', 'corridor_0', 'garage_0', 'storage_room_1'],
        'storage_room_1': ['storage_room_0'],
    },
    'Ihlen_1_int': {
        'bathroom_0': ['corridor_0'],
        'bedroom_0': ['corridor_0'],
        'bedroom_1': ['corridor_0', 'staircase_0'],
        'bedroom_2': ['corridor_0'],
        'corridor_0': ['bathroom_0', 'bedroom_0', 'bedroom_1', 'bedroom_2', 'kitchen_0', 'living_room_0'],
        'dining_room_0': ['kitchen_0', 'living_room_0'],
        'kitchen_0': ['corridor_0', 'dining_room_0', 'staircase_0'],
        'living_room_0': ['corridor_0', 'dining_room_0'],
        'staircase_0': ['bedroom_1', 'kitchen_0'],
    },
    'Merom_0_int': {
        'bathroom_0': ['living_room_0'],
        'childs_room_0': ['living_room_0'],
        'living_room_0': ['bathroom_0', 'childs_room_0', 'playroom_0'],
        'playroom_0': ['living_room_0', 'staircase_0', 'storage_room_0'],
        'staircase_0': ['playroom_0'],
        'storage_room_0': ['playroom_0', 'utility_room_0'],
        'utility_room_0': ['storage_room_0'],
    },
    'Merom_1_int': {
        'bathroom_0': ['corridor_0'],
        'bedroom_0': ['corridor_0'],
        'childs_room_0': ['corridor_0'],
        'corridor_0': ['bathroom_0', 'bedroom_0', 'childs_room_0', 'kitchen_0', 'living_room_0', 'staircase_0'],
        'dining_room_0': ['kitchen_0', 'living_room_0'],
        'kitchen_0': ['corridor_0', 'dining_room_0'],
        'living_room_0': ['corridor_0', 'dining_room_0', 'staircase_0'],
        'staircase_0': ['corridor_0', 'living_room_0'],
    },
    'Pomaria_0_int': {
        'bathroom_0': ['corridor_0'],
        'bedroom_0': ['corridor_0'],
        'bedroom_1': ['corridor_0'],
        'corridor_0': ['bathroom_0', 'bedroom_0', 'bedroom_1', 'home_office_0', 'television_room_0'],
        'home_office_0': ['corridor_0'],
        'television_room_0': ['corridor_0'],
    },
    'Pomaria_1_int': {
        'bathroom_0': ['corridor_0'],
        'corridor_0': ['bathroom_0', 'kitchen_0', 'living_room_0', 'pantry_room_0', 'utility_room_0'],
        'kitchen_0': ['corridor_0'],
        'living_room_0': ['corridor_0'],
        'pantry_room_0': ['corridor_0'],
        'utility_room_0': ['corridor_0'],
    },
    'Pomaria_2_int': {
        'bathroom_0': ['bedroom_0'],
        'bedroom_0': ['bathroom_0', 'corridor_0'],
        'corridor_0': ['bedroom_0'],
    },
    'Wainscott_1_int': {
        'bedroom_0' : ['corridor_0', 'bathroom_0'],
        'bedroom_1' : ['corridor_0'],
        'bedroom_2' : ['corridor_0'],
        'bathroom_0' : [ 'bedroom_0' ],
        'bathroom_1' : ['corridor_0'],
        'exercise_room_0' : ['corridor_0'],
        'corridor_0': ['utility_room_0', 'playroom_0', 'bedroom_0', 'bedroom_1', 'bedroom_2', 'bathroom_1', 'exercise_room_0'],
        'utility_room_0': ['corridor_0'],
        'playroom_0': ['home_office_0', 'corridor_0'],
        'home_office_0': ['playroom_0']
    }
}
